spring:
  application:
    name: 4.6-discovery-eureka-ha
security:
  basic:
    enabled: true # 开启基于http basic的认证
  user:
    name: wsws0521
    password: 123
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
